"""AnomalyEvent and Report writer.

Writes per-run output to:
  reports/<run_id>/
    events.jsonl        — one JSON line per flagged frame
    frames/<idx>.jpg    — thumbnail of flagged frames
    clips/<idx>.mp4     — optional pre/post clips (when save_clips=True)
    index.html          — HTML summary generated by html_writer
"""
from __future__ import annotations

import dataclasses
import json
import time
import uuid
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any

import cv2
import numpy as np

from graphics_validator.detectors.base import Flag
from graphics_validator.utils.logging import get_logger

log = get_logger(__name__)


@dataclass
class AnomalyEvent:
    """Represents one detected anomaly event."""

    run_id: str
    frame_idx: int
    timestamp_s: float
    flags: list[dict]        # serialised Flag objects
    vlm_response: dict | None = None
    thumb_path: str | None = None
    clip_path: str | None = None


@dataclass
class Report:
    """Accumulates events and writes the final report to disk.

    Parameters
    ----------
    run_dir:
        Root directory for this run's output.
    save_thumbs:
        Whether to write JPEG thumbnails for flagged frames.
    save_clips:
        Whether to write MP4 clip segments around flagged frames.
    thumb_width:
        Width (pixels) to rescale thumbnails.
    clip_pre_frames / clip_post_frames:
        Number of frames before/after the flagged frame to include in a clip.
    """

    run_dir: Path
    save_thumbs: bool = True
    save_clips: bool = False
    thumb_width: int = 320
    clip_pre_frames: int = 30
    clip_post_frames: int = 30

    events: list[AnomalyEvent] = field(default_factory=list, init=False)

    def __post_init__(self) -> None:
        self.run_dir = Path(self.run_dir)
        self.run_dir.mkdir(parents=True, exist_ok=True)
        if self.save_thumbs:
            (self.run_dir / "frames").mkdir(exist_ok=True)
        if self.save_clips:
            (self.run_dir / "clips").mkdir(exist_ok=True)

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def record(
        self,
        frame_idx: int,
        timestamp_s: float,
        flags: list[Flag],
        frame_bgr: np.ndarray | None = None,
        vlm_response: dict | None = None,
    ) -> AnomalyEvent:
        """Record one flagged frame and return the :class:`AnomalyEvent`."""
        thumb_path: str | None = None
        if self.save_thumbs and frame_bgr is not None:
            thumb_path = self._save_thumb(frame_bgr, frame_idx)

        event = AnomalyEvent(
            run_id=self.run_dir.name,
            frame_idx=frame_idx,
            timestamp_s=round(timestamp_s, 3),
            flags=[asdict(f) for f in flags],
            vlm_response=vlm_response,
            thumb_path=thumb_path,
        )
        self.events.append(event)
        self._append_jsonl(event)
        return event

    def finalise(self) -> None:
        """Write the HTML summary index after all frames have been processed."""
        from graphics_validator.reporting.html_writer import write_html  # noqa: PLC0415

        write_html(self)
        log.info(f"Report written to {self.run_dir}")

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _save_thumb(self, frame_bgr: np.ndarray, idx: int) -> str:
        h, w = frame_bgr.shape[:2]
        new_w = min(self.thumb_width, w)
        new_h = int(h * new_w / w)
        thumb = cv2.resize(frame_bgr, (new_w, new_h))
        path = self.run_dir / "frames" / f"{idx:06d}.jpg"
        cv2.imwrite(str(path), thumb, [cv2.IMWRITE_JPEG_QUALITY, 85])
        return str(path.relative_to(self.run_dir))

    def _append_jsonl(self, event: AnomalyEvent) -> None:
        jsonl_path = self.run_dir / "events.jsonl"
        with jsonl_path.open("a", encoding="utf-8") as fh:
            fh.write(json.dumps(asdict(event)) + "\n")


def make_report(cfg: dict | None = None, out_dir: Path | str = "reports") -> Report:
    """Create a :class:`Report` for a new run, using config values."""
    c = (cfg or {}).get("reporting", {})
    run_id = f"{time.strftime('%Y%m%d_%H%M%S')}_{uuid.uuid4().hex[:6]}"
    run_dir = Path(out_dir) / run_id
    return Report(
        run_dir=run_dir,
        save_thumbs=c.get("save_thumbs", True),
        save_clips=c.get("save_clips", False),
        thumb_width=c.get("thumb_width", 320),
        clip_pre_frames=c.get("clip_pre_frames", 30),
        clip_post_frames=c.get("clip_post_frames", 30),
    )
